CREATE TABLE fleet_data (
    vehicle_id VARCHAR(50),
    trip_id VARCHAR(50),
    driver_id VARCHAR(50),
    fleet_name VARCHAR(100),
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    distance_km FLOAT,
    route_type VARCHAR(20),
    fuel_consumption FLOAT,
    fuel_efficiency_km_l FLOAT,
    fuel_type VARCHAR(20),
    engine_temp_avg FLOAT,
    tire_pressure_avg FLOAT,
    battery_voltage_avg FLOAT,
    engine_warnings INT,
    brake_warnings INT,
    oil_quality FLOAT CHECK (oil_quality BETWEEN 0.0 AND 1.0),
    maintenance_required BOOLEAN,
    avg_speed_kmh FLOAT,
    max_speed_kmh FLOAT,
    harsh_braking_count INT,
    harsh_acceleration_count INT,
    idling_time_min FLOAT,
    weather_condition VARCHAR(20),
    outside_temperature FLOAT,
    road_condition VARCHAR(20)
);
